model:
  params:
    # vaflow_ckpt_path : "/root/workspace/vaflow/log/2025_02_18-23_57_33-vaflow_sda_dit_noise/ckpt/epoch=0074-step=1.71e+05.ckpt"
    # vaflow_ckpt_path : "/root/workspace/vaflow/log/2025_02_26-22_26_55-vaflow_sda_dit_custom_ddpm_small_ddpm/ckpt/epoch=0079-step=3.65e+05.ckpt"
    vaflow_ckpt_path : Null
    ignore_keys: []
    guidance_scale          : 5.0
    sample_steps            : 30
    num_samples_per_prompt  : 1
    sample_scheduler_config :
      # ckpt_dir_pipline_scheduler: 
      # target: diffusers.DDIMScheduler
      # params:
      #   num_train_timesteps : 1000
      #   beta_start          : 0.0015
      #   beta_end            : 0.0195
      #   beta_schedule       : linear 
      #   prediction_type     : v_prediction
      target: diffusers.DPMSolverMultistepScheduler
      params:
        num_train_timesteps : 1000
        beta_start          : 0.0015
        beta_end            : 0.0195
        beta_schedule       : linear 
        solver_order        : 2
        algorithm_type      : 'dpmsolver++'



infer_data:
  # ckpt_path           : "/root/workspace/vaflow/log/2025_02_08-11_17_40-vaflow_sda_dit_joint_tune_vae/ckpt/epoch=0089-step=2.18e+05.ckpt"
  ckpt_path           : Null
  batch_size          : 15
  num_workers         : 5
  prefetch_factor     : 2
  persistent_workers  : False
  collate_fn          : Null
  
  target            : dataset.video.VideoDataset
  params:
    # Dataset params
    verbose             : False
    load_mode_meta      : Null
    load_mode_item      : video_feat_with_waveform
    meta_dir            : "/data_mount/vadio/meta/vggsound_split_withaudiosetrhythm_mp4xclipb16xibva_docker"
    # load_mode_item      : video_feat_cavp_with_waveform
    # meta_dir            : "/data_mount/vadio/meta/vggsound_split_withaudiosetrhythm_mp4xclipb16xibvaxcavpv_docker"
    # split               : test_sample_3k                        
    split               : test                  
    # Audio video params
    audio_process_config : ${data.audio_process}
    video_process_config : ${data.video_process}



lightning:
  logger:
    target        : pytorch_lightning.loggers.wandb.WandbLogger
    params: 
      project     : VAFlow 
      group       : infer  
      # name        : bridge_dit_base_time_adaln_animatediff_audioldm_perceiver_cubic_aa