model:
  params:
    vaflow_ckpt_path : "/root/workspace/vaflow/log/2025_02_18-13_18_10-vaflow_sda_dit_uncond_joint_tune_vae/ckpt/epoch=0059-step=1.71e+05.ckpt"
    ignore_keys: []
    guidance_scale          : 5.0
    sample_steps            : 25
    sample_method           : dopri5
    num_samples_per_prompt  : 1



infer_data:
  ckpt_path           : Null
  batch_size          : 30
  num_workers         : 20
  prefetch_factor     : 2
  persistent_workers  : False
  collate_fn          : Null
  
  target            : dataset.video.VideoDataset
  params:
    # Dataset params
    verbose             : False
    load_mode_meta      : Null
    load_mode_item      : video_feat_with_waveform
    meta_dir            : "/data_mount/vadio/meta/vggsound_split_withaudiosetrhythm_mp4xclipb16xibva_docker"
    # split               : test_sample_3k                        
    split               : test                        
    # Audio video params
    audio_process_config : ${data.audio_process}
    video_process_config : ${data.video_process}



lightning:
  logger:
    target        : pytorch_lightning.loggers.wandb.WandbLogger
    params: 
      project     : VAFlow 
      group       : infer  
      # name        : bridge_dit_base_time_adaln_animatediff_audioldm_perceiver_cubic_aa